### PR TITLE
fix: update timeout example.

### LINKED ISSUE #12: Getting error with the following code
panic: Can't run remote command: dial tcp: i/o timeout

``` go
package main

import (
        "fmt"

        "github.com/appleboy/easyssh-proxy"
)

func main() {
        // Create MakeConfig instance with remote username, server address and path to private key.
        ssh := &easyssh.MakeConfig{
                Server: "localhost",
                // Optional key or Password without either we try to contact your agent SOCKET
                //Password: "password",
                Key:     "/.ssh/id_rsa",
                Port:    "22",
                Timeout: 60,
        }

        // Call Run method with command you want to run on remote server.
        stdout, stderr, done, err := ssh.Run("ls -al", 60)
        // Handle errors
        if err != nil {
                panic("Can't run remote command: " + err.Error())
        } else {
                fmt.Println("don is :", done, "stdout is :", stdout, ";   stderr is :", stderr)
        }

}
```

### PR DESCRIPTION
**Pull request by appleboy**
fix #12

### CODE REVIEW

**Comment by zhujinhe** [comment]
need to update the example to:
```
60 * time.Second
```

https://github.com/appleboy/easyssh-proxy/blob/c087e1d9358a5fae549b9d39073ab084ec005853/example/ssh/ssh.go#L29

**Comment by appleboy** [comment]
@zhujinhe I will take it.

**Comment by appleboy** [comment]
or you can send the PR?

**Comment by appleboy** [comment]
@zhujinhe fixed in https://github.com/appleboy/easyssh-proxy/commit/8dc53bb50b6f620642c2dd551f328180baf46781

**Pull request merged**
